name: Test

on:
  push:
    branches: [ master ]  # Disparar o workflow quando houver push na branch main
  pull_request:
    branches: [ master ]  # Disparar o workflow quando houver pull request para a branch main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
      
    - name: Create virtual environment
      run: python -m venv venv
      
    - name: Activate virtual environment
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
      
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
      
    - name: Test code
      run: |
        python main.py