name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.5"
      
    - name: Create virtual environment
      run: python -m venv venv
      
    - name: Activate virtual environment
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
      
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
      
    - name: Test code
      run: |
        python main.py